defaults:  
  - _self_

# ## whether test a single file or a directory
# inFile: akira.json
# CTI_Source: AVERTIUM

## compare inSet with ground_truth_set
inSet: d:/BBBB/graduation project/project/CTINexus-toolkit-main1/dataset/Merger-output-large-GT

## output evaluation results into the outSet
outSet: d:/BBBB/graduation project/project/CTINexus-toolkit-main1/dataset/Merger-output-large-GT-proc