defaults:  
  - _self_

# ## whether test a single file or a directory
# inFile: akira.json
# CTI_Source: AVERTIUM

## compare inSet with ground_truth_set
ground_truth_set: d:/BBBB/graduation project/project/CTINexus-toolkit-main1/dataset/Tagger-output-gpt4-8-v2
inSet: d:/BBBB/graduation project/project/CTINexus-toolkit-main1/Eval/RQ3/Tagger/GPT3.5-1shot

## output evaluation results into the outSet
outSet: d:/BBBB/graduation project/project/CTINexus-toolkit-main1/Eval/RQ3/Tagger/GPT3.5-1shot
outMetricSet: d:/BBBB/graduation project/project/CTINexus-toolkit-main1/Eval/RQ3/Tagger/GPT3.5-1shot/prompt_store/metrics

shot: 1
base_model: gpt-3.5-0125