defaults:  
  - _self_

# ## whether test a single file or a directory
# inFile: akira.json
# CTI_Source: AVERTIUM

## compare inSet with ground_truth_set
ground_truth_set: d:/BBBB/graduation project/project/CTINexus-toolkit-main1/dataset/Tagger-output-gpt4-8-v2-processed
inSet: d:/BBBB/graduation project/project/CTINexus-toolkit-main1/Eval/RQ3/Tagger/GPT3.5-12shot

## output evaluation results into the outSet
outSet: d:/BBBB/graduation project/project/CTINexus-toolkit-main1/Eval/RQ3/Tagger/GPT3.5-12shot
outMetricSet: d:/BBBB/graduation project/project/CTINexus-toolkit-main1/Eval/RQ3/Tagger/GPT3.5-12shot/prompt_store/metrics

shot: 12
base_model: gpt-3.5-turbo-0125