defaults:  
  - _self_

# inFile: 
# CTI_source: 
inSet: d:/BBBB/graduation project/project/CTINexus-toolkit-main1/dataset/RE-IE-outputs-3-asc
outSet: d:/BBBB/graduation project/project/CTINexus-toolkit-main1/Eval/RQ3/Tagger/GPT4-4shot

# OpenAI setting
model: gpt-4-0125-preview
api_key: <YOUR_OPENAI_KEY>

# Prompt setting
tag_prompt_folder: Toolbox/TagPrompt
tag_prompt_file: 4shot-v2.jinja
tag_prompt_store: d:/BBBB/graduation project/project/CTINexus-toolkit-main1/Eval/RQ3/Tagger/GPT4-4shot/prompt_store
shot: 4