defaults:  
  - _self_

# inFile: 
# CTI_source: 
inSet: d:/BBBB/graduation project/project/CTINexus-toolkit-main1/dataset/RE-IE-outputs-3-asc  ##ground truth of triplet extraction
outSet: d:/BBBB/graduation project/project/CTINexus-toolkit-main1/Eval/RQ4/Tagger/qwen-1shot ##destination of tagger output

# OpenAI setting
model: qwen-plus
api_key: sk-47f2d862adf74ade822f5db3c5a6a2c1

# Prompt setting
tag_prompt_folder: Toolbox/TagPrompt
tag_prompt_file: 1shot.jinja
tag_prompt_store: d:/BBBB/graduation project/project/CTINexus-toolkit-main1/Eval/RQ3/Tagger/GPT4-1shot/prompt_store
shot: 1