defaults:  
  - _self_

# CTI_Source: AVERTIUM
# inFile: akira-S18-NL2.json
inSet: d:/BBBB/graduation project/project/CTINexus-toolkit-main1/dataset/Tagger-output-gpt4-8-v2-processed
outSet: d:/BBBB/graduation project/project/CTINexus-toolkit-main1/Eval/RQ3/Merger/Embedding/Merger-output-0.6-secureBert
api_key: <YOUR_OPENAI_KEY>
embedding_model: secure-bert
similarity_threshold: 0.6