defaults:  
  - _self_

# CTI_Source: AVERTIUM
# inFile: akira.json
inSet: d:/BBBB/graduation project/project/CTINexus-toolkit-main1/dataset/Merger-output-large-GT
outSet: d:/BBBB/graduation project/project/CTINexus-toolkit-main1/Eval/RQ3/Linker/0-shot-gpt-4

## oepnai config
model: gpt-4-0125-preview
api_key: <YOUR_OPENAI_KEY>


## prompt constructor
link_prompt_folder: Toolbox/LinkerPrompt
link_prompt_file: 0-shot.jinja
shot: 0

## prompt store
link_prompt_set: d:/BBBB/graduation project/project/CTINexus-toolkit-main1/Eval/RQ3/Linker/0-shot-gpt-4/prompt_store/metrics