defaults:  
  - _self_

addition:
  securityweek:
    - pwn2own.json
    - wallescape.json
  thehackernews:
    - ESG.json
  threatPost:
    - H0lyGh0st.json
  trendmicro:
    - Akira.json

# CTI_Source: AVERTIUM
# inFile: akira.json
inSet: d:/BBBB/graduation project/project/CTINexus-toolkit-main1/dataset/Merger-output-large-GT
outSet: d:/BBBB/graduation project/project/CTINexus-toolkit-main1/Eval/RQ3/Linker/2-shot-gpt-4

## oepnai config
model: qwen-omni-turbo
api_key: sk-47f2d862adf74ade822f5db3c5a6a2c1
url: https://dashscope.aliyuncs.com/compatible-mode/v1


## prompt constructor
link_prompt_folder: Toolbox/LinkerPrompt
link_prompt_file: 2-shot.jinja
shot: 2

## prompt store
link_prompt_set: d:/BBBB/graduation project/project/CTINexus-toolkit-main1/Eval/RQ3/Linker/2-shot-gpt-4/prompt_store/metrics