defaults:  
  - _self_

# CTI_Source: AVERTIUM
inSet: d:/BBBB/graduation project/project/CTINexus-toolkit-main1/Eval/RQ3/Linker/1-shot-gpt-4
outSet: d:/BBBB/graduation project/project/CTINexus-toolkit-main1/Eval/RQ3/Linker/1-shot-gpt-4
GTSet: d:/BBBB/graduation project/project/CTINexus-toolkit-main1/dataset/Linker-outputs-GT

embedding_model: text-embedding-3-large
api_key: <YOUR_OPENAI_KEY>
thresh: 0.45